### ISSUE TITLE
Showcase: Update documentation for legacy machines

### ISSUE THREAD

**Issue by DasbachVDMA** [umati/Showcase#45]
UserStory:
Legacy machines using the VPN (fairconnect.umati.app managed) are connected via 1-1 clients, bypassing the datahub.
Describe the architecture for legacy users.

**Comment by GoetzGoerisch** [comment]
@DasbachVDMA @ccvca as the Datahub is currently already not working sufficiently I would like to stop it already for HMI and use only the VPN connected machines with 1-1 clients for May and June.

Any thoughts? I have a list of all connected machines. @ccvca  is there an easy way to generate configs for this machines?

**Comment by ccvca** [comment]
Due to the number of machines, it will be the only feasible solution, to generate the configurations...
The configurations will require the following information:

- Identifier (e.g. IswSample) for the client name
- OPC UA Endpoint (IP + Port)
- OPC UA Username (if any)
- OPC UA Password (if any)
- OPC UA Security Mode

The format should be "machine readable". The easiest way would be a JSON file(s), a CSV should also work. (Separator Character should not be part of any other value) In the end any format, which can be easily accessed by a Python script should work.

**Comment by GoetzGoerisch** [comment]
Obsolete, we are not recreating 1-1 clients for legacy machines in the new deployment.
